services:
  - type: web
    name: thrustvault-server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: COGNITO_USER_POOL_ID
        sync: false
      - key: COGNITO_CLIENT_ID
        sync: false
      - key: COGNITO_CLIENT_SECRET
        sync: false
      - key: COGNITO_REGION
        value: eu-north-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: APP_BASE_URL
        value: https://thrustvault.bharani-01.xyz
      - key: SESSION_SECRET
        generateValue: true
