import os
import sys

# Try to import pptx, install if missing
try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN
except ImportError:
    print("python-pptx is not installed. Please run: pip install python-pptx")
    sys.exit(1)

def create_presentation():
    prs = Presentation()
    
    # Set slide dimensions to widescreen (16:9)
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)
    
    # Layouts: 6 is a blank slide layout
    blank_layout = prs.slide_layouts[6]
    
    # Define Colors
    c_dark_navy = RGBColor(15, 23, 42)    # #0f172a
    c_royal_blue = RGBColor(37, 99, 235)  # #2563eb
    c_slate_gray = RGBColor(71, 85, 105)  # #475569
    c_white = RGBColor(255, 255, 255)
    c_light_bg = RGBColor(248, 250, 252)  # #f8fafc
    c_success_green = RGBColor(5, 150, 105) # #059669
    
    # Helper to add a colored background to a slide
    def set_slide_background(slide, color):
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = color

    # Helper to create a textbox
    def add_textbox(slide, left, top, width, height, text="", font_name="Arial", font_size=18, font_color=c_dark_navy, bold=False, align=PP_ALIGN.LEFT):
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.word_wrap = True
        tf.margin_left = Inches(0)
        tf.margin_right = Inches(0)
        tf.margin_top = Inches(0)
        tf.margin_bottom = Inches(0)
        
        p = tf.paragraphs[0]
        p.text = text
        p.alignment = align
        p.font.name = font_name
        p.font.size = Pt(font_size)
        p.font.color.rgb = font_color
        p.font.bold = bold
        return txBox, tf

    # Helper to add standard slide with Title and Left/Right columns
    def add_standard_slide(title, subtitle=None):
        slide = prs.slides.add_slide(blank_layout)
        set_slide_background(slide, c_light_bg)
        
        # Title
        add_textbox(slide, Inches(0.8), Inches(0.6), Inches(11.7), Inches(0.8), 
                    text=title, font_name="Arial", font_size=32, font_color=c_dark_navy, bold=True)
        
        # Subtitle
        if subtitle:
            add_textbox(slide, Inches(0.8), Inches(1.3), Inches(11.7), Inches(0.4), 
                        text=subtitle, font_name="Arial", font_size=16, font_color=c_royal_blue, bold=False)
            
        # Subtle horizontal divider line
        shape = slide.shapes.add_shape(
            1, # Rectangle
            Inches(0.8), Inches(1.8), Inches(11.7), Inches(0.02)
        )
        shape.fill.solid()
        shape.fill.fore_color.rgb = c_royal_blue
        shape.line.fill.background()
        
        return slide

    # ==========================================
    # SLIDE 1: Title Slide (Dark Theme)
    # ==========================================
    slide_1 = prs.slides.add_slide(blank_layout)
    set_slide_background(slide_1, c_dark_navy)
    
    # Title
    add_textbox(slide_1, Inches(1.0), Inches(2.2), Inches(11.33), Inches(1.5),
                text="ThrustVault", font_name="Arial", font_size=64, font_color=c_white, bold=True)
    
    # Accent slash / subtext
    add_textbox(slide_1, Inches(1.0), Inches(3.6), Inches(11.33), Inches(0.8),
                text="UAV Powertrain Calibration & Analytics Console", font_name="Arial", font_size=24, font_color=c_royal_blue, bold=True)
    
    # Footer info
    add_textbox(slide_1, Inches(1.0), Inches(5.5), Inches(11.33), Inches(0.8),
                text="Enterprise UAV Powertrain Engineering Database\nPowered by Supabase native auth & analytics curves", 
                font_name="Arial", font_size=14, font_color=c_slate_gray, bold=False)

    # ==========================================
    # SLIDE 2: Project Vision & Engineering Challenges
    # ==========================================
    slide_2 = add_standard_slide("Project Vision & Objectives", "Why ThrustVault was created")
    
    # Left column: The Problem
    _, tf_left = add_textbox(slide_2, Inches(0.8), Inches(2.2), Inches(5.5), Inches(4.5))
    p1 = tf_left.paragraphs[0]
    p1.text = "The Challenge in UAV Powertrain Testing"
    p1.font.bold = True
    p1.font.size = Pt(20)
    p1.font.color.rgb = c_royal_blue
    
    bullets_left = [
        "Calibration data for UAV motors & propellers is highly fragmented.",
        "Engineers manually copy/paste throttle steps, voltage, thrust, RPM, and temperature outputs.",
        "Spreadsheets generated by testing rigs (like Rotrix) are unstructured and hard to query.",
        "No centralized storage leads to lost performance histories and repeated tests."
    ]
    for b in bullets_left:
        p = tf_left.add_paragraph()
        p.text = "• " + b
        p.font.size = Pt(15)
        p.space_before = Pt(10)
        
    # Right column: The Solution
    _, tf_right = add_textbox(slide_2, Inches(7.0), Inches(2.2), Inches(5.5), Inches(4.5))
    p2 = tf_right.paragraphs[0]
    p2.text = "The ThrustVault Solution"
    p2.font.bold = True
    p2.font.size = Pt(20)
    p2.font.color.rgb = c_success_green
    
    bullets_right = [
        "A centralized SQL database hosting motor catalogs and performance readings.",
        "Interactive analytics dashboard plotting multi-propeller calibration curves.",
        "A smart spreadsheet uploader that automatically maps columns, detects runs, and imports data points.",
        "Role-based secure access for admins, interns, and guests."
    ]
    for b in bullets_right:
        p = tf_right.add_paragraph()
        p.text = "• " + b
        p.font.size = Pt(15)
        p.space_before = Pt(10)

    # ==========================================
    # SLIDE 3: Architecture & Technology Stack
    # ==========================================
    slide_3 = add_standard_slide("Architecture & Tech Stack", "Modern, lightweight, and scalable SPA design")
    
    # Add 4 column boxes representing stack components
    width_col = Inches(2.7)
    gap = Inches(0.3)
    start_left = Inches(0.8)
    
    components = [
        {
            "title": "Database Layer",
            "tech": "Supabase PostgreSQL",
            "color": c_success_green,
            "items": ["Centralized relational storage", "Profiles, motors, runs & points tables", "Robust Foreign Key cascades", "Dynamic JSONB extra_data column"]
        },
        {
            "title": "Backend Services",
            "tech": "Flask & Supabase SDK",
            "color": c_royal_blue,
            "items": ["Statics server rendering SPA pages", "Supabase authentication bridges", "Environment variables configuration injection"]
        },
        {
            "title": "Analytics Frontend",
            "tech": "Vanilla JS & Chart.js",
            "color": c_dark_navy,
            "items": ["Zero-framework SPA speed", "Comparative curve generation", "Dynamic axis metric mapping", "Fluid UI transitions"]
        },
        {
            "title": "Ingestion Engine",
            "tech": "SheetJS (xlsx)",
            "color": RGBColor(219, 100, 4), # orange-ish
            "items": ["Client-side spreadsheet loading", "HTML-to-XLS table parser", "Merges pre-resolving", "Multi-run grouping"]
        }
    ]
    
    for idx, comp in enumerate(components):
        left_pos = start_left + idx * (width_col + gap)
        # Background box
        box = slide_3.shapes.add_shape(1, left_pos, Inches(2.2), width_col, Inches(4.5))
        box.fill.solid()
        box.fill.fore_color.rgb = c_white
        box.line.color.rgb = comp["color"]
        box.line.width = Pt(1.5)
        
        # Text frame inside the box
        tf = box.text_frame
        tf.word_wrap = True
        tf.margin_left = Inches(0.15)
        tf.margin_right = Inches(0.15)
        tf.margin_top = Inches(0.15)
        
        p = tf.paragraphs[0]
        p.text = comp["title"]
        p.font.bold = True
        p.font.size = Pt(16)
        p.font.color.rgb = comp["color"]
        
        p_sub = tf.add_paragraph()
        p_sub.text = comp["tech"]
        p_sub.font.bold = True
        p_sub.font.size = Pt(13)
        p_sub.font.color.rgb = c_slate_gray
        p_sub.space_after = Pt(10)
        
        for item in comp["items"]:
            pi = tf.add_paragraph()
            pi.text = "• " + item
            pi.font.size = Pt(11)
            pi.font.color.rgb = c_dark_navy
            pi.space_before = Pt(6)

    # ==========================================
    # SLIDE 4: Interactive Powertrain Catalog
    # ==========================================
    slide_4 = add_standard_slide("UAV Powertrain Catalog", "Unified catalog tracking motor metrics and classes")
    
    _, tf_left = add_textbox(slide_4, Inches(0.8), Inches(2.2), Inches(5.5), Inches(4.5))
    p = tf_left.paragraphs[0]
    p.text = "Key Catalog Features"
    p.font.bold = True
    p.font.size = Pt(20)
    p.font.color.rgb = c_royal_blue
    
    bullets = [
        "Structured categorization by thrust level classes (e.g. 5kg, 10kg, 15kg Class).",
        "Tracks details including Motor KV, Weight, Max Current, and Max Thrust.",
        "Interactive tables featuring search, sorting, and dynamic category filtering.",
        "Role-based Action Controls: Admins/Interns see creation/editing tools, Guests see read-only listings."
    ]
    for b in bullets:
        p = tf_left.add_paragraph()
        p.text = "• " + b
        p.font.size = Pt(15)
        p.space_before = Pt(10)
        
    # Right column: visual box / callout
    box_r = slide_4.shapes.add_shape(1, Inches(7.0), Inches(2.2), Inches(5.5), Inches(4.0))
    box_r.fill.solid()
    box_r.fill.fore_color.rgb = c_dark_navy
    box_r.line.fill.background()
    tf_br = box_r.text_frame
    tf_br.word_wrap = True
    tf_br.margin_left = Inches(0.3)
    tf_br.margin_top = Inches(0.4)
    
    p = tf_br.paragraphs[0]
    p.text = "Data Consistency & Deletions Cascading"
    p.font.bold = True
    p.font.size = Pt(18)
    p.font.color.rgb = c_white
    p.space_after = Pt(15)
    
    points = [
        "Foreign Key cascades ensure deleting a motor automatically cleans up its test runs and data points.",
        "Integrates dynamic count badges in the sidebar showing database stats instantly.",
        "Allows direct comparisons of multiple motors side-by-side in a comparative overlay."
    ]
    for pt in points:
        p = tf_br.add_paragraph()
        p.text = "→ " + pt
        p.font.size = Pt(13)
        p.font.color.rgb = c_light_bg
        p.space_before = Pt(8)

    # ==========================================
    # SLIDE 5: Calibration Curves & Analytics
    # ==========================================
    slide_5 = add_standard_slide("Calibration Curves & Analytics", "Converting raw readings into engineering insights")
    
    # Left Box
    box_l = slide_5.shapes.add_shape(1, Inches(0.8), Inches(2.2), Inches(5.5), Inches(4.0))
    box_l.fill.solid()
    box_l.fill.fore_color.rgb = c_white
    box_l.line.color.rgb = c_royal_blue
    box_l.line.width = Pt(1.5)
    tf_bl = box_l.text_frame
    tf_bl.word_wrap = True
    tf_bl.margin_left = Inches(0.2)
    tf_bl.margin_top = Inches(0.2)
    
    p = tf_bl.paragraphs[0]
    p.text = "Multi-Propeller Comparison Plots"
    p.font.bold = True
    p.font.size = Pt(18)
    p.font.color.rgb = c_royal_blue
    p.space_after = Pt(10)
    
    points_l = [
        "Dynamically plots multiple propellers for the same motor on a single chart.",
        "Allows analyzing efficiency profiles across different powertrain setups.",
        "Utilizes a responsive Chart.js layout supporting smooth tooltip animations."
    ]
    for pt in points_l:
        p = tf_bl.add_paragraph()
        p.text = "• " + pt
        p.font.size = Pt(13)
        p.font.color.rgb = c_dark_navy
        p.space_before = Pt(8)
        
    # Right Box
    box_r = slide_5.shapes.add_shape(1, Inches(7.0), Inches(2.2), Inches(5.5), Inches(4.0))
    box_r.fill.solid()
    box_r.fill.fore_color.rgb = c_white
    box_r.line.color.rgb = c_royal_blue
    box_r.line.width = Pt(1.5)
    tf_br = box_r.text_frame
    tf_br.word_wrap = True
    tf_br.margin_left = Inches(0.2)
    tf_br.margin_top = Inches(0.2)
    
    p = tf_br.paragraphs[0]
    p.text = "Supported Metrics (Y-Axis)"
    p.font.bold = True
    p.font.size = Pt(18)
    p.font.color.rgb = c_royal_blue
    p.space_after = Pt(10)
    
    metrics = [
        "Thrust (g) vs. Throttle (%)",
        "Efficiency (g/W) vs. Thrust (g)  [Crucial for flight time models]",
        "Current (A) vs. Throttle (%)      [Crucial for ESC selection]",
        "RPM vs. Throttle (%)"
    ]
    for m in metrics:
        p = tf_br.add_paragraph()
        p.text = "📊 " + m
        p.font.size = Pt(13)
        p.font.color.rgb = c_dark_navy
        p.space_before = Pt(8)

    # ==========================================
    # SLIDE 6: Advanced Dataset Creator
    # ==========================================
    slide_6 = add_standard_slide("Advanced Dataset Creator", "Frictionless ingestion and mapping workspace")
    
    _, tf_left = add_textbox(slide_6, Inches(0.8), Inches(2.2), Inches(5.5), Inches(4.5))
    p = tf_left.paragraphs[0]
    p.text = "Spreadsheet Ingestion Workspace"
    p.font.bold = True
    p.font.size = Pt(20)
    p.font.color.rgb = c_royal_blue
    
    bullets = [
        "Decodes binary Excel (XLSX/XLS) and CSV files directly in the browser.",
        "Special HTML parser trims and imports legacy sheets containing embedded HTML tables.",
        "Resolves merged cells automatically using structural merges (!merges) - propagates KV types and propellers across throttle steps.",
        "Detects and splits multi-run sheets (e.g. 7 propellers in 1 file) showing a Run Selector Modal."
    ]
    for b in bullets:
        p = tf_left.add_paragraph()
        p.text = "• " + b
        p.font.size = Pt(14)
        p.space_before = Pt(8)
        
    _, tf_right = add_textbox(slide_6, Inches(7.0), Inches(2.2), Inches(5.5), Inches(4.5))
    p = tf_right.paragraphs[0]
    p.text = "Interactive Column Mapper"
    p.font.bold = True
    p.font.size = Pt(20)
    p.font.color.rgb = c_royal_blue
    
    bullets_r = [
        "Opens an interactive edit screen for every uploaded file.",
        "Allows mapping any sheet column to standard fields, metadata fields, or ignoring it.",
        "Allows defining custom columns (saved inside Supabase extra_data JSONB column).",
        "No repeated column validator blocks duplicate mappings.",
        "Includes a sheet preview showing the first 10 rows of data.",
        "Supports direct copy-paste (Ctrl+V) from Excel and a header-based Copy Down tool."
    ]
    for b in bullets_r:
        p = tf_right.add_paragraph()
        p.text = "• " + b
        p.font.size = Pt(14)
        p.space_before = Pt(8)

    # ==========================================
    # SLIDE 7: Security & Access Control
    # ==========================================
    slide_7 = add_standard_slide("Security & Access Control", "Enterprise-grade authorization and authentication")
    
    _, tf_left = add_textbox(slide_7, Inches(0.8), Inches(2.2), Inches(5.5), Inches(4.5))
    p = tf_left.paragraphs[0]
    p.text = "Supabase Native Auth & Roles"
    p.font.bold = True
    p.font.size = Pt(20)
    p.font.color.rgb = c_royal_blue
    
    bullets = [
        "Authenticates users directly using secure JSON Web Tokens (JWT).",
        "Matches user profiles in a custom user_profiles database table.",
        "Role-based boundaries: Admins (Full write/catalog CRUD), Interns (Write test runs only), Guests (Read-only catalog & curves)."
    ]
    for b in bullets:
        p = tf_left.add_paragraph()
        p.text = "• " + b
        p.font.size = Pt(15)
        p.space_before = Pt(10)
        
    # Right column: Password Reset OTP
    _, tf_right = add_textbox(slide_7, Inches(7.0), Inches(2.2), Inches(5.5), Inches(4.5))
    p = tf_right.paragraphs[0]
    p.text = "Forgot Password & OTP Flow"
    p.font.bold = True
    p.font.size = Pt(20)
    p.font.color.rgb = c_success_green
    
    bullets_r = [
        "Features a premium multi-step password reset flow within the login card.",
        "Integrates Supabase Passwordless OTP: requests a secure 6-digit code via email.",
        "Validates the OTP code on-screen to establish a temporary session.",
        "Updates the password securely and signs out immediately to enforce clean credentials."
    ]
    for b in bullets_r:
        p = tf_right.add_paragraph()
        p.text = "• " + b
        p.font.size = Pt(15)
        p.space_before = Pt(10)

    # ==========================================
    # SLIDE 8: Project Impact & Future Scope
    # ==========================================
    slide_8 = add_standard_slide("Project Impact & Future Scope", "Looking ahead")
    
    _, tf_left = add_textbox(slide_8, Inches(0.8), Inches(2.2), Inches(5.5), Inches(4.5))
    p = tf_left.paragraphs[0]
    p.text = "Key Project Impacts"
    p.font.bold = True
    p.font.size = Pt(20)
    p.font.color.rgb = c_royal_blue
    
    bullets = [
        "Drastically reduces data entry times (from minutes to single-click imports).",
        "Minimizes errors caused by manual cell transcription.",
        "Centralizes engineering test histories, making them searchable and comparable.",
        "Ensures data consistency and provides clean role-based isolation."
    ]
    for b in bullets:
        p = tf_left.add_paragraph()
        p.text = "• " + b
        p.font.size = Pt(15)
        p.space_before = Pt(10)
        
    _, tf_right = add_textbox(slide_8, Inches(7.0), Inches(2.2), Inches(5.5), Inches(4.5))
    p = tf_right.paragraphs[0]
    p.text = "Future Roadmap"
    p.font.bold = True
    p.font.size = Pt(20)
    p.font.color.rgb = c_royal_blue
    
    bullets_r = [
        "Adding support for multi-motor curves overlay (plotting curves of different motors together).",
        "Integrating export options (export selected curve readings back to XLSX or PDF reports).",
        "Connecting directly to powertrain test stands via Bluetooth/Serial APIs for live data streaming."
    ]
    for b in bullets_r:
        p = tf_right.add_paragraph()
        p.text = "• " + b
        p.font.size = Pt(15)
        p.space_before = Pt(10)

    # Save
    out_name = "ThrustVault_Project_Presentation.pptx"
    prs.save(out_name)
    print(f"Presentation saved successfully as {out_name}")

if __name__ == "__main__":
    create_presentation()
