import os
import glob
import re

directory = r'd:\motor data\admin_portal\public'

navbar_override_css = (
    "\n    /* ================================================================\n"
    "       ADMIN PORTAL LAYOUT OVERRIDE — Horizontal Topbar Navigation\n"
    "       The sidebar renders as a full-width horizontal topbar, not a\n"
    "       280px left panel. app-container stacks vertically.\n"
    "    ================================================================ */\n"
    "    .app-container {\n"
    "        flex-direction: column !important;\n"
    "        height: 100vh !important;\n"
    "        overflow: hidden !important;\n"
    "    }\n"
    "    .sidebar {\n"
    "        width: 100% !important;\n"
    "        height: auto !important;\n"
    "        min-height: 60px !important;\n"
    "        border-right: none !important;\n"
    "        border-bottom: 1px solid var(--border-color) !important;\n"
    "        flex-direction: row !important;\n"
    "        align-items: center !important;\n"
    "        padding: 0 24px !important;\n"
    "        background-color: rgba(255,255,255,0.95) !important;\n"
    "        backdrop-filter: blur(12px) !important;\n"
    "        -webkit-backdrop-filter: blur(12px) !important;\n"
    "        box-shadow: 0 1px 4px rgba(15,23,42,0.06) !important;\n"
    "        gap: 0 !important;\n"
    "        flex-shrink: 0 !important;\n"
    "        z-index: 100 !important;\n"
    "        position: relative !important;\n"
    "        box-sizing: border-box !important;\n"
    "    }\n"
    "    [data-theme=dark] .sidebar {\n"
    "        background-color: rgba(15,23,42,0.95) !important;\n"
    "        border-bottom-color: rgba(255,255,255,0.07) !important;\n"
    "    }\n"
    "    .sidebar .sidebar-skeleton-wrapper {\n"
    "        display: flex !important;\n"
    "        flex-direction: row !important;\n"
    "        align-items: center !important;\n"
    "        gap: 16px !important;\n"
    "        width: 100% !important;\n"
    "        padding: 0 !important;\n"
    "        height: 60px !important;\n"
    "    }\n"
    "    .main-content-wrapper {\n"
    "        flex: 1 !important;\n"
    "        min-height: 0 !important;\n"
    "        display: flex !important;\n"
    "        flex-direction: column !important;\n"
    "    }\n"
    "    .main-content {\n"
    "        flex: 1 !important;\n"
    "        min-height: 0 !important;\n"
    "    }\n"
    "    /* Nav link styles for horizontal bar */\n"
    "    .sidebar .btn-sidebar-link {\n"
    "        padding: 8px 14px !important;\n"
    "        border-radius: var(--radius-md) !important;\n"
    "        font-size: 0.875rem !important;\n"
    "        font-weight: 500 !important;\n"
    "        color: var(--text-secondary) !important;\n"
    "        white-space: nowrap !important;\n"
    "        display: inline-flex !important;\n"
    "        align-items: center !important;\n"
    "        gap: 6px !important;\n"
    "        transition: all 0.18s ease !important;\n"
    "        text-decoration: none !important;\n"
    "        background: transparent !important;\n"
    "        border: none !important;\n"
    "        cursor: pointer !important;\n"
    "    }\n"
    "    .sidebar .btn-sidebar-link:hover,\n"
    "    .sidebar .btn-sidebar-link.active {\n"
    "        background: rgba(37,99,235,0.08) !important;\n"
    "        color: var(--primary-color) !important;\n"
    "    }\n"
    "    /* Dropdown items in horizontal nav */\n"
    "    .sidebar .sidebar-dropdown-wrapper .category-list {\n"
    "        display: none !important;\n"
    "        position: absolute !important;\n"
    "        top: calc(100% + 4px) !important;\n"
    "        left: 0 !important;\n"
    "        min-width: 200px !important;\n"
    "        background: var(--bg-panel-solid) !important;\n"
    "        border: 1px solid var(--border-color) !important;\n"
    "        border-radius: var(--radius-md) !important;\n"
    "        box-shadow: 0 8px 24px -4px rgba(15,23,42,0.12) !important;\n"
    "        z-index: 9999 !important;\n"
    "        padding: 6px !important;\n"
    "        flex-direction: column !important;\n"
    "        gap: 2px !important;\n"
    "    }\n"
    "    .sidebar .sidebar-dropdown-wrapper.expanded .category-list {\n"
    "        display: flex !important;\n"
    "    }\n"
    "    .sidebar .sidebar-dropdown-wrapper .category-list .btn-sidebar-link {\n"
    "        width: 100% !important;\n"
    "        text-align: left !important;\n"
    "        justify-content: flex-start !important;\n"
    "        padding: 9px 14px !important;\n"
    "    }\n"
    "    /* User profile dropdown */\n"
    "    .user-profile-menu-wrapper {\n"
    "        position: relative !important;\n"
    "        display: flex !important;\n"
    "        align-items: center !important;\n"
    "        margin-left: auto !important;\n"
    "    }\n"
    "    .user-avatar-trigger {\n"
    "        display: flex !important;\n"
    "        align-items: center !important;\n"
    "        gap: 6px !important;\n"
    "        cursor: pointer !important;\n"
    "        padding: 4px 8px !important;\n"
    "        border-radius: var(--radius-md) !important;\n"
    "        transition: background 0.15s ease !important;\n"
    "    }\n"
    "    .user-avatar-trigger:hover { background: rgba(37,99,235,0.06) !important; }\n"
    "    .user-dropdown-card {\n"
    "        display: none !important;\n"
    "        position: absolute !important;\n"
    "        top: calc(100% + 8px) !important;\n"
    "        right: 0 !important;\n"
    "        min-width: 220px !important;\n"
    "        background: var(--bg-panel-solid) !important;\n"
    "        border: 1px solid var(--border-color) !important;\n"
    "        border-radius: var(--radius-md) !important;\n"
    "        box-shadow: 0 8px 24px -4px rgba(15,23,42,0.12) !important;\n"
    "        z-index: 9999 !important;\n"
    "        padding: 12px !important;\n"
    "        flex-direction: column !important;\n"
    "        gap: 10px !important;\n"
    "    }\n"
    "    .user-profile-menu-wrapper.open .user-dropdown-card { display: flex !important; }\n"
    "    .dropdown-user-details { display: flex !important; flex-direction: column !important; gap: 4px !important; }\n"
    "    .badge-role { font-size: 0.72rem !important; font-weight: 700 !important; padding: 2px 8px !important; border-radius: var(--radius-full) !important; display: inline-block !important; width: fit-content !important; }\n"
    "    .role-admin { background: #dbeafe; color: #1d4ed8 !important; }\n"
    "    .dropdown-divider { height: 1px; background: var(--border-color); margin: 4px 0; }\n"
    "    .sidebar .sidebar-footer {\n"
    "        border-top: none !important;\n"
    "        background: transparent !important;\n"
    "        padding: 0 !important;\n"
    "        gap: 0 !important;\n"
    "    }\n"
    "    .avatar-chevron { width: 14px !important; height: 14px !important; color: var(--text-secondary) !important; transition: transform 0.2s ease !important; }\n"
    "    .user-profile-menu-wrapper.open .avatar-chevron { transform: rotate(180deg) !important; }\n"
    "    .sidebar .btn-logout-premium { width: 100% !important; padding: 8px 14px !important; font-size: 0.82rem !important; margin-top: 8px !important; }\n"
    "    /* Sidebar nav dropdown wrappers need relative position for dropdown to work */\n"
    "    .sidebar .sidebar-nav { overflow: visible !important; flex: none !important; }\n"
    "\n"
)

count = 0
for fpath in glob.glob(os.path.join(directory, '*.html')):
    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Remove any existing admin-layout-override style block
    content = re.sub(
        r'<style id="admin-layout-override"[^>]*>.*?</style>',
        '',
        content,
        flags=re.DOTALL
    )

    # Inject override just before </head>
    override_block = '<style id="admin-layout-override">' + navbar_override_css + '</style>'
    if '</head>' in content:
        content = content.replace('</head>', override_block + '\n</head>', 1)
        with open(fpath, 'w', encoding='utf-8') as f:
            f.write(content)
        count += 1
        print(f'Updated: {os.path.basename(fpath)}')

print(f'Done. {count} files updated.')
